<a href="https://colab.research.google.com/github/Harshavardhan123-cloud/ML/blob/master/TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
pip install --upgrade pip


     |████████████████████████████████| 1.6MB 27.6MB/s 
  Found existing installation: pip 19.3.1
    Uninstalling pip-19.3.1:
      Successfully uninstalled pip-19.3.1


In [4]:
pip install tensorflow

In [5]:
pip install tf-nightl

ERROR: Could not find a version that satisfies the requirement tf-nightl (from versions: none)
ERROR: No matching distribution found for tf-nightl


In [6]:

import tensorflow as tf   

In [9]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [10]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [11]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.17849606, -0.33721256, -0.14396548, -0.34457636, -0.9963599 ,
        -0.5585207 ,  0.40352792,  0.4515651 ,  0.33452678, -0.00591711]],
      dtype=float32)

In [12]:
tf.nn.softmax(predictions).numpy()

array([[0.12094314, 0.07221241, 0.08760683, 0.0716826 , 0.03735492,
        0.05787605, 0.15146466, 0.15891819, 0.14136586, 0.10057536]],
      dtype=float32)

In [13]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)


In [14]:

loss_fn(y_train[:1], predictions).numpy()

2.8494515

In [15]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [17]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.4925 - accuracy: 0.8563
Epoch 2/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1574 - accuracy: 0.9528
Epoch 3/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1134 - accuracy: 0.9666
Epoch 4/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0897 - accuracy: 0.9719
Epoch 5/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0715 - accuracy: 0.9782


In [18]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0773 - accuracy: 0.9766


[0.07732547074556351, 0.9765999913215637]

In [19]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [20]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[8.14439449e-09, 6.16785123e-10, 7.58477154e-06, 3.32337426e-04,
        1.52528226e-10, 1.12189389e-06, 1.83180531e-14, 9.99638200e-01,
        8.94401921e-08, 2.06367658e-05],
       [6.14931821e-08, 2.79003551e-04, 9.99691129e-01, 2.92015757e-05,
        1.59501767e-15, 1.06603096e-07, 8.54740563e-08, 2.29156548e-15,
        3.59837941e-07, 4.88000222e-12],
       [2.98439318e-08, 9.99644756e-01, 3.38345599e-05, 1.42141917e-05,
        1.92516363e-05, 1.04236960e-06, 1.53498986e-05, 1.59875664e-04,
        1.09820794e-04, 1.72890043e-06],
       [9.98736441e-01, 1.47177881e-10, 1.04360282e-04, 6.00387239e-07,
        7.10887349e-08, 9.78074422e-06, 2.39470857e-04, 8.81285871e-07,
        3.44354106e-07, 9.07984155e-04],
       [2.73406476e-06, 6.87886026e-10, 1.09911089e-05, 1.59546303e-07,
        9.65107262e-01, 9.99934215e-08, 4.15337269e-07, 1.20515586e-04,
        1.88820081e-06, 3.47559229e-02]], dtype=float32)>